Repository jeju-deers/jeju-deers-frontend, pull requests merged in 2024-12, with the labels that each got.

#63 [#59] build: 깃허브 페이지로 배포
  package.json
  pnpm-lock.yaml
  src/common/components/templates/NewsWrite.tsx
  src/hooks/myPage/mutate/useUpdateUserInformation.ts
  src/hooks/myPage/useEditMyPage.tsx
  src/routes/Router.tsx
  vite.config.ts
Labels: build

#62 [#52] feat: 게시글 작성 기능 구현
  src/api/write.ts
  src/common/components/atom/board/CkEditor.tsx
  src/common/components/templates/NewsWrite.tsx
  src/common/hooks/write/mutate/usePostWrite.ts
  src/hooks/login/mutate/usePostLogin.ts
  src/pages/teamroom/WorkoutSchedulePage.tsx
  src/pages/teamroom/WorkoutSchedulePageStyles.ts
Labels: feat

#70 [#60] style: 관리자 페이지 UI 구현
  src/assets/images/dropdown_down_arrow.svg
  src/assets/images/dropdown_up_arrow.svg
  src/assets/images/jeju_deers_text.svg
  src/assets/images/user_management.svg
  src/components/atoms/admin/Header.tsx
  src/components/atoms/admin/HeaderStyles.ts
  src/components/atoms/admin/SideBar.tsx
  src/components/atoms/admin/SideBarStyles.ts
  src/components/atoms/admin/content/DropDown.tsx
  src/components/atoms/admin/content/DropDownStyles.ts
  src/components/atoms/admin/content/ListHeaderSection.tsx
  src/components/atoms/admin/content/ListHeaderSectionStyles.ts
  src/components/atoms/admin/content/ListItemSection.tsx
  src/components/atoms/admin/content/ListItemSectionStyles.ts
  src/constants/authorityData.ts
  src/constants/belongData.ts
  src/constants/commentTemporaryData.ts
  src/constants/userInformationData.ts
  src/constants/userTypeData.ts
  src/pages/admin/AdminPage.tsx
  src/pages/admin/AdminPageStyles.ts
  src/routes/Router.tsx
  tailwind.config.cjs
Labels: style

#73 [#67] feat: 관리자 페이지 사용자 목록 조회 api 및 기능 구현
  src/api/users.ts
  src/hooks/admin/query/useGetUsersInformation.ts
  src/pages/admin/AdminPage.tsx
Labels: feat

#74 [#68] feat: 관리자 페이지의 사용자 목록 삭제 기능 구현
  src/constants/userInformationData.ts
  src/pages/admin/AdminPage.tsx
Labels: feat

#65 [#64] feat: 게시판 일괄 적용
  src/api/account.ts
  src/common/components/atom/board/CkEditor.tsx
  src/common/components/atom/board/WriteButton.tsx
  src/common/components/atom/board/WriteDropDownButton.tsx
  src/common/components/templates/BoardWrite.tsx
  src/common/components/templates/BoardWriteStyle.ts
  src/components/templates/common/CommonBoard.tsx
  src/components/templates/community/GuestBoard.tsx
  src/components/templates/community/Media.tsx
  src/components/templates/community/Support.tsx
  src/components/templates/news/news/News.tsx
  src/components/templates/teamroom/CoachBoard.tsx
  src/components/templates/teamroom/MembershipFee.tsx
  src/components/templates/teamroom/PlayBook.tsx
  src/components/templates/teamroom/StaffBoard.tsx
  src/components/templates/teamroom/TeamBoard.tsx
  src/components/templates/teamroom/WorkoutSchedules.tsx
  src/constants/writeOption.ts
  src/hooks/login/mutate/usePostLogin.ts
  src/pages/common/BoardWritePage.tsx
  src/pages/common/NewsWritePage.tsx
  src/routes/Router.tsx
Labels: feat

#77 [#76] bugfix: 관리자 페이지 사용자 삭제 checkbox 이슈 해결
  src/constants/constants.ts
  src/constants/userInformationData.ts
  src/pages/admin/AdminPage.tsx
Labels: bugfix
